### ISSUE TITLE
Can you provide other language please,my great god?

### ISSUE THREAD

**Issue by ScienceZone** [hmaster20/M3Ueditor#1]
Hello, friend, you know, not everyone understand Russian. I know the Russian people are very friendly ,so can you offer the English version?

**Comment by ScienceZone** [comment]
Hello, friend, you know, not everyone understand Russian. I know the Russian people are very friendly ,so can you offer the English version?

**Comment by hmaster20** [comment]
Hello! Yes, I have thoughts about translating the program into another language.
Now I'm working on a program for support the English language.

**Comment by hmaster20** [comment]
Released version of the program with the support of English.
