### ISSUE TITLE
Проблемы с плейлистом

### ISSUE THREAD

**Issue by Cryo777** [hmaster20/M3Ueditor#2]
#EXTM3U url-tvg="http://web.web/xmltv.xml" deinterlace=7 распознается как канал
При сохранении плейлиста название канала копируется из tvg-name
Удаляет любые другие теги которых не знает aspect-ratio=4:3 croppadd=5x5

**Comment by hmaster20** [comment]
Привет. Ошибку копирования tvg-name и неверного чтения #EXTM3U устранил.
Опиши механизм работы с дополнительными тегами. Куда ты их вводишь? А куда следует? Опиши формат создания строки #EXTM3U ... Он произвольный или может содержать строго типизированные теги?

**Comment by Cryo777** [comment]
Привет.  
Доп теги я брал от сюда http://borpas.info/iptvplayer-docs#6 там есть описание тегов.

Мой плейлист выглядит так: 

`#EXTM3U url-tvg="http://web.web/xmltv.xml" deinterlace=7
#EXTINF:1720 tvg-name="5 канал (Россия) (+2)" tvg-logo="http://web.web/1720.png?w=250&h=250" aspect-ratio=4:3 group-title="Эфирные",5 канал +2
http://web.web/web.php?channel=1720
#EXTINF:1740 tvg-name="5 канал (Россия) (+4)" tvg-logo="http://web.web/1740.png?w=250&h=250" group-title="Эфирные",5 канал +4
http://web.web/web.php?channel=1740
#EXTINF:3450 tvg-name="Еврокино" tvg-logo="http://web.web/3450.png?w=250&h=250" aspect-ratio=4:3 croppadd=0x131 group-title="Фильмы и Сериалы",Еврокино HD
http:/web.web/web.php?channel=3450
#EXTINF:3451 tvg-name="Иллюзион+" tvg-logo="http://web.web/3451.png?w=250&h=250" aspect-ratio=4:3 croppadd=0x131 group-title="Фильмы и Сериалы",Иллюзион+ HD
http://web.web/web.php?channel=3451
#EXTINF:245 tvg-name="ZeeTV Россия" tvg-logo="http://web.web/245.png?w=250&h=250" aspect-ratio=16:9 group-title="Фильмы и Сериалы",ZeeTV
http://web.web/web.php?channel=245`
